### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by wertyui6795**
we need to put in our own files, and i would like to meet again face-to-face to develop more.

### CODE REVIEW

**Comment by AppsToKnow** [comment]
Thanks for the email. I am not real sure what you're trying to tell me. However, it will be this weekend before I get a chance to look at things. 

I will try to set something up for fifth block sometime next week.

Thank you. 

Michael Stephenson

**Comment by wertyui6795** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android" ... >
    <uses-sdk android:minSdkVersion="4" android:targetSdkVersion="15" />
    ...
</manifest>

to use Android

<?xml version="1.0" encoding="utf-8"?>

<manifest>

```
<uses-permission />
<permission />
<permission-tree />
<permission-group />
<instrumentation />
<uses-sdk />
<uses-configuration />  
<uses-feature />  
<supports-screens />  
<compatible-screens />  
<supports-gl-texture />  

<application>

    <activity>
        <intent-filter>
            <action />
            <category />
            <data />
        </intent-filter>
        <meta-data />
    </activity>

    <activity-alias>
        <intent-filter> . . . </intent-filter>
        <meta-data />
    </activity-alias>

    <service>
        <intent-filter> . . . </intent-filter>
        <meta-data/>
    </service>

    <receiver>
        <intent-filter> . . . </intent-filter>
        <meta-data />
    </receiver>

    <provider>
        <grant-uri-permission />
        <meta-data />
        <path-permission />
    </provider>

    <uses-library />

</application>
```

</manifest>

MANIFEST.XML file

**Comment by wertyui6795** [comment]
http://developer.android.com/guide/topics/manifest/manifest-intro.html
http://developer.android.com/training/basics/supporting-devices/platforms.html
http://android-developers.blogspot.com/2012/11/designing-for-tablets-were-here-to-help.html

**Comment by AppsToKnow** [comment]
Thanks for the links. I will look at them this weekend. 

Thank you. 

Michael Stephenson

**Comment by wertyui6795** [comment]
Hello, I would like to copy the files for ios, and edit them to fit android. Please allow me to edit these files....　　🐲🐯　thanks!!!

**Comment by AppsToKnow** [comment]
Attached are the files. I know that you intended me to post these to GitHub, but I haven’t gotten the hang of it yet. We will need to go over this when we get together next week.

Let me know if there are any other files that you need, as I might have missed something.

Michael.

**Comment by wertyui6795** [comment]
Hello, i am adding new files to my version in my Repo. please check it out.

--ethan--

**Pull request merged**
